### ISSUE TITLE
About the compatibility version

### ISSUE THREAD

**Issue by Anm-pinellia** [chengtan9907/OpenSTL#138] opened 2024-05-30 11:31 UTC
Thanks for your kind work, i found that current version may raise error in my environments. I tried to find out the source of this issue usually comes from timm and pytorch-lightning. Though I tried to fix them by modifying some codes, but i am afraid of some other issues. Can you give more information about the current OpenSTL framework, like timm, pytorch-lightning, torch version?

**Comment by Anm-pinellia** [comment] 2024-05-30 11:37
For example, my timm version is 1.0.3, pytorch-lightning 2.1.0, OpenSTL 1.0.0. I found that current OpenSTL use timm's lrscheduler, and it will raise error "TypeError: step() missing 1 required positional argument: 'epoch'". This is cause by OpenSTL try to call scheduler.step() with its pytorch-lightning process flow, but cosinescheduler timm in this version must receive a params of epoch.

**Comment by chengtan9907** [comment] 2024-07-30 01:11
The issue is not related to the version. There are some conflicts between timm and lightning in the scheduler. This bug was addressed in the latest commit; you can refer to [commit#96a1c77](https://github.com/chengtan9907/OpenSTL/commit/96a1c7795e1b886f23e69b36944efd705e9e33e2).

**Closed as completed by chengtan9907** 2024-07-30 01:11 UTC
